### ISSUE TITLE
https://www.nuget.org/packages/FAKE points to wrong url regarding migration guide

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FAKE#2766]
On https://www.nuget.org/packages/FAKE, the information link about the deprecation points to 404.

I'm not sure how to fix this? @forki 

It should point to https://fake.build/guide/fake-migrate-to-fake-5.html not https://fake.build/fake-migrate-to-fake-5.html

It is probably only on nuget.org that it can be changed, I don't see the matching message in the repository.

**Comment by xperiandri** [comment]
Yes, there must be a new package released

**Comment by xperiandri** [comment]
@sergey-tihon if you give me access to manage that NuGet package I will download the existing, fix its content and publish an update with build version changed

**Comment by sergey-tihon** [comment]
there is no need to release a package to update the deprecation message.
fixed.

**Comment by xperiandri** [comment]
@sergey-tihon will it change after some time?
I still see the old URL
![image](https://github.com/fsprojects/FAKE/assets/2365592/d3d5923c-fe0a-41df-9dbe-5527ef32d846)

**Comment by sergey-tihon** [comment]
@xperiandri I see a new one on your screenshoot.

**Comment by xperiandri** [comment]
Ah it finally updated after several Ctrl+R 😄
